- name: Remove telemetry packages
  ansible.builtin.apt:
    name:
      - apport
      - popularity-contest
      - ubuntu-report
      - whoopsie
    autoremove: true
    state: absent
    purge: true

- name: Block telemetry domains
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
  loop: "{{ telemetry_domains + telemetry_domains | map('regex_replace', '^', 'www.') | list }}"

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install oci-cli
  ansible.builtin.pip:
    name: oci-cli
    state: present
