- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install oci-cli
  ansible.builtin.pip:
    name: oci-cli
    state: present
