- name: Remove telemetry packages
  ansible.builtin.apt:
    name:
      - apport
      - popularity-contest
      - ubuntu-report
      - whoopsie
    autoremove: true
    state: absent
    purge: true

- name: Remove bloat
  ansible.builtin.apt:
    name:
      - ubuntu-advantage-tools
    autoremove: true
    state: absent
    purge: true

- name: Install oracle cloud agent for monitoring
  community.general.snap:
    name: oracle-cloud-agent
    classic: true
    state: present

- name: Block telemetry domains
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
  loop: "{{ setup_telemetry_domains | map('regex_replace', '^', 'www.') | list }}"

- name: Remove MOTD noise
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 10-help-text
    - 50-motd-news
    - 80-livepatch
    - 88-esm-announce
    - 91-contract-ua-esm-status
    - 95-hwe-eol

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true

# Install pipx by using GitHub release as the package in the LTS repos is out of date: https://github.com/pypa/pipx/issues/1524
- name: Install pipx from GitHub
  ansible.builtin.include_tasks: pipx.yml

- name: Install oci-cli
  community.general.pipx:
    name: oci-cli
    state: present
    global: true
    executable: /usr/local/bin/pipx

- name: Configure rsyslog to redirect cron logs
  ansible.builtin.lineinfile:
    path: "/etc/rsyslog.d/50-default.conf"
    line: "cron.*    {{ setup_cron_log }}"
