- name: Build Fress RSS OCI Image
  hosts: all
  become: true
  vars_files:
    - vault.yml
  roles:
    - role: setup
    - role: security
    - role: geerlingguy.mysql
      vars:
        mysql_databases:
          - name: freshrss
            encoding: utf8
            collation: utf8_general_ci
        mysql_root_password: "{{ mysql.root }}"
        mysql_users:
          - name: freshrss
            password: "{{ mysql.freshrss }}"
            priv: '*.*:ALL,GRANT'
            host: localhost
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
        docker_install_compose: false
    - role: nginx
    - role: freshrss
    - role: fulltextrss
    - role: nitter
    - role: redlib
    - role: planka
    - role: logrotate
      vars:
        logrotate_services:
          - name: freshrss
            logs:
              - "{{ freshrss_feed_update_log.dest }}"
              - "{{ freshrss_install_dir }}/data/users/_/log.txt"
              - "{{ freshrss_install_dir }}/data/users/{{ freshrss.user }}/log.txt"
              - "{{ nginx_logs_directory }}/freshrss.access.log"
              - "{{ nginx_logs_directory }}/freshrss.error.log"
          - name: fulltextrss
            logs:
              - "{{ nginx_logs_directory }}/fulltextrss.access.log"
              - "{{ nginx_logs_directory }}/fulltextrss.error.log"
          - name: nginx
            logs:
              - "{{ nginx_logs_directory }}/error.log"
          - name: nitter
            logs:
              - "{{ nginx_logs_directory }}/nitter.access.log"
              - "{{ nginx_logs_directory }}/nitter.error.log"
          - name: redlib
            logs:
              - "{{ nginx_logs_directory }}/redlib.access.log"
              - "{{ nginx_logs_directory }}/redlib.error.log"
          - name: planka
            logs:
              - "{{ nginx_logs_directory }}/planka.access.log"
              - "{{ nginx_logs_directory }}/planka.error.log"
    - role: cleanup
