- name: Build Fress RSS OCI Image
  hosts: all
  become: true
  vars_files:
    - vault.yml
  roles:
    - role: setup
    - role: security
    - role: geerlingguy.mysql
      vars:
        mysql_databases:
          - name: freshrss
            encoding: utf8
            collation: utf8_general_ci
        mysql_root_password: "{{ mysql_root_pass }}"
        mysql_users:
          - name: freshrss
            password: "{{ mysql_freshrss_pass }}"
            priv: '*.*:ALL,GRANT'
            host: localhost
    - role: nginx
    - role: freshrss
    - role: fulltextrss
    - role: nitter
    - role: cleanup
