# Needs to be Dockerised due to free version of fulltext_rss only supporting legacy PHP5.
# credit to https://github.com/heussd/fivefilters-full-text-rss-docker/tree/master
# for building/maintaining a working docker image

- name: Create install directory
  ansible.builtin.file:
    path: "{{ fulltextrss_install_dir }}"
    state: directory
    mode: '0700'

- name: Put custom configuration in place
  ansible.builtin.template:
    src: custom_config.php.j2
    dest: "{{ fulltextrss_install_dir }}/{{ fulltextrss_config_file }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0700'

- name: Fetch latest version of site configurations
  ansible.builtin.git:
    repo: https://github.com/fivefilters/ftr-site-config.git
    dest: "{{ fulltextrss_install_dir }}/{{ fulltextrss_config_dir }}"
    version: 'master'
    depth: 1

- name: Set permissions for site configuration
  ansible.builtin.file:
    path: "{{ fulltextrss_install_dir }}/{{ fulltextrss_config_dir }}"
    state: directory
    recurse: true
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '700'

- name: Set port number to use
  ansible.builtin.set_fact:
    fulltextrss_port: "{{ 5000 + range(0, 4999) | random }}"

- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ fulltextrss_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0700'

- name: Create Nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_confd_directory }}/fulltextrss.conf"
    mode: '0644'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: Restart nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    state: restarted

- name: Fetch latest docker image
  ansible.builtin.command: docker compose pull
  args:
    chdir: "{{ fulltextrss_install_dir }}"
  changed_when: true

- name: Start service
  ansible.builtin.command: docker compose up --detach
  args:
    chdir: "{{ fulltextrss_install_dir }}"
  changed_when: true
