- name: Setup iptables
  ansible.builtin.include_tasks: firewall.yml

- name: Setup AppArmor
  ansible.builtin.include_tasks: apparmor.yml

- name: Setup tailscale
  ansible.builtin.include_tasks: tailscale.yml
