- name: Create backup directory
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Setup user backup job (every day at 12:55 AM)
  ansible.builtin.cron:
    name: "Create backup"
    weekday: "*"
    hour: "0"
    minute: "55"
    user: root
    job: "tar -zcvf {{ backup_dir }}/$(date +'%Y-%m-%d_%H-%M-%S').tar.gz -C {{ install_dir }} data/users"

- name: Setup DB backup cronjob (every day at 1AM)
  ansible.builtin.cron:
    name: MySQL Backup
    weekday: "*"
    hour: "1"
    minute: "0"
    user: root
    job: "mysqldump --skip-comments --user=root --password='{{ mysql_root_pass }}' --all-databases > \"{{ backup_dir }}/$(date +'%Y-%m-%d_%H-%M-%S').sql\""

- name: Create restore tool
  ansible.builtin.template:
    src: restore.sh.j2
    dest: /bin/freshrss_restore
    owner: root
    group: root
    mode: "0701"
