name: Build & Keep

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: 0 2 * * *

permissions:
  contents: read

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3

      - uses: ./.github/actions/packer
        with:
          fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
          hcpClientID: "${{ secrets.HCP_CLIENT_ID }}"
          hcpClientSecret: "${{ secrets.HCP_CLIENT_SECRET }}"
          keepImage: true
          privateKey: "${{ secrets.OCI_PRIVATE_KEY }}"
          region: "${{ vars.OCI_REGION }}"
          subnetOCID: "${{ secrets.SUBNET_OCID }}"
          rootTenancyOCID: "${{ secrets.ROOT_TENANCY_OCID }}"
          terraformTenancyOCID: "${{ secrets.TERRAFORM_TENANCY_OCID }}"
          userOCID: "${{ secrets.OCI_USER_OCID }}"
