name: Packer
description: Builds and tests packer image using Terratest
author: batinicaz

inputs:
  ansibleVaultPass:
    description: The password to access the encrypted ansible vault
    required: true
  fingerprint:
    description: OCI fingerpint
    required: true
  hcpClientID:
    description: HCP client ID
    required: true
  hcpClientSecret:
    description: HCP client secret
    required: true
  keepImage:
    description: Keep the image available if tests pass?
    default: 'false'
    required: false
  privateKey:
    description: OCI private key
    required: true
  region:
    description: OCI region
    required: true
  subnetOCID:
    description: OCI subnet
    required: true
  rootTenancyOCID:
    description: OCI root tenancy
    required: true
  terraformTenancyOCID:
    description: OCI terraform tenancy
    required: true
  userOCID:
    description: OCI user
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3

    - name: Decrypt ansible vault
      run: >
        docker run --rm -v "$(pwd):/work" -w /work
        ghcr.io/batinicaz/packer:latest sh -c
        'echo ${{ inputs.ansibleVaultPass }} > vault-pass &&
        ansible-vault decrypt --vault-password-file vault-pass packer/ansible/vault.yml;
        rm vault-pass'
      shell: bash

    - name: Set delete flag
      run: |
        deleteFlag=''
        if [[ "${{ inputs.keepImage }}" != "true" ]]; then
          deleteFlag='-deleteImage'
        fi
        echo DELETE_FLAG=${deleteFlag} >> $GITHUB_ENV
      shell: bash

    - name: Set hcpBucketName flag
      run: |
        hcpBucketName='gha-branch-build'
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          hcpBucketName='stable'
        fi
        echo BUCKET_NAME=${hcpBucketName} >> $GITHUB_ENV
      shell: bash

    - name: Set version flag
      run: echo "VERSION=${{ github.ref_name }}-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      shell: bash

    - name: Build
      run: >
        docker run --rm -v "$(pwd):/work" -w /work
        ghcr.io/batinicaz/packer:latest sh -c
        'echo ${{ inputs.ansibleVaultPass }} > packer/tests/.vault-password &&
        go test -timeout 1h -v ./packer/tests ${{ env.DELETE_FLAG }}
        -hcpBucketName ${{ env.BUCKET_NAME }}
        -fingerprint "${{ inputs.fingerprint }}"
        -hcpClientID "${{ inputs.hcpClientID }}"
        -hcpClientSecret "${{ inputs.hcpClientSecret }}"
        -privateKey "${{ inputs.privateKey }}"
        -region "${{ inputs.region }}"
        -subnetOCID "${{ inputs.subnetOCID }}"
        -rootTenancyOCID "${{ inputs.rootTenancyOCID }}"
        -terraformTenancyOCID "${{ inputs.terraformTenancyOCID }}"
        -userOCID "${{ inputs.userOCID }}"
        -version "${{ env.VERSION }}";
        rm packer/tests/.vault-password &&
        git config --global --add safe.directory /work &&
        git checkout packer/ansible/vault.yml'
      shell: bash
